# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/sustainabledb
spring.datasource.username=root
spring.datasource.password=root

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# SERVER PORT (use one free port)
# ===============================
server.port=8080